litellm_settings:
  set_verbose: true

model_list:
  - model_name: vertex_gemini_pro
    litellm_params:
      provider: vertex_ai
      model: vertex_ai/gemini-2.5-pro
      vertex_project: fra-ai-testing-noprod 
      vertex_location: europe-west1

  - model_name: vertex_gemini_flash
    litellm_params:
      provider: vertex_ai
      model: vertex_ai/gemini-2.5-flash
      vertex_project: fra-ai-testing-noprod 
      vertex_location: europe-west1
