model_list:
  - model_name: vertex_ai
    litellm_params:
      provider: vertex_ai
      model: vertex_ai/gemini-2.5-pro 
      vertex_project: fra-ai-testing-noprod 
      vertex_location: europe-west1
      drop_params: true
      # Uses GCP credentials from environment
